export const ELEMENT_ALREADY_EXIST = 'Element already exist';
export const USER_ALREADY_EXIST = 'User already exist. Please login';
export const USER_NOT_FOUND = 'User not found';
export const PRODUCT_NOT_FOUNT = 'Product not found'
export const REQUIRED_INPUTS = 'All input is required';
export const REQUIRED_TOKEN = 'A token is required for authentication';
export const INVALID_CREDENTIALS = 'Invalid Credentials';
export const INVALID_TOKEN = 'Invalid Token';
export const INVALID_EMAIL = 'Invalid Email';
export const INVALID_PRICE = 'Invalid Price';
export const UNKNOWN_ERROR = 'Something went wrong';
